### ISSUE TITLE
Cakephp integration

### ISSUE THREAD

**Issue by nisha-kajale** [Highstrike/cakephp-solr-datasource#2]
Hi i want to integrate solarium with new version of cakephp.
Can you please help?

**Comment by highstrike** [comment]
Greetings,

I have no clue how to write a datasource for cake 3.x as of yet because all my projects are running on cake 2.x. 

You can either [write it by yourself](https://github.com/cakephp/docs/issues/3253) or use Solarium directly in cake.

**Comment by nisha-kajale** [comment]
Hi,

Can you help we use lower version of cakephp?
Or can you tell me how to use solarium directly with cakephp?

Thanks,
Nisha

**Comment by highstrike** [comment]
Greetings,

You can use [Solarium](http://www.solarium-project.org/) directly by downloading it through composer, and then adding the `include(ROOT . DS . 'location_to_composer_vendor_dir/autoload.php');` to your Controller.

You can then start using the [Solarium API functions](http://wiki.solarium-project.org/index.php/V3:Basic_usage) in your controller actions.

**Comment by nisha-kajale** [comment]
Hi,

I added solarium folder in vendor directory.

And added include require ROOT . DS . 'vendor' . DS . 'autoload.php';
But still I am getting error Class 'App\Controller\Solarium\Client' not found 

In controller. 
How to fix?

**Comment by highstrike** [comment]
Cake3 uses namespaces.

Use this code instead `$client = new \Solarium\Client($config);`
Notice the `\` before `Solarium`
