### ISSUE TITLE
Using Solr DataSource to bake

### ISSUE THREAD

**Issue by Quezako** [Highstrike/cakephp-solr-datasource#3]
Hello,

I'm trying to use the SolR DataSource to do a bake all.
I've set SolrSource à $default.

But I'm having this message:

> Your database does not have any tables.

**Comment by highstrike** [comment]
Hi,

I haven't even considered using bake with Solr, i'm not entirely sure if its even possible.

You should probably bake with your mysql database by default and then use this plugin afterwards your project is baked and ready to go :+1:

**Comment by Quezako** [comment]
Good idea.

but with the MySQL DB, I've got this error message:

> Possible Models based on your current database:
> 1. Boite
> 2. CentreDeService
> 3. Collaborateur
> 4. Contrat
> 5. Engagement
> 6. Livrable
> 7. Pointage
> 8. Projet
> 9. Reference
> 10. Reporting
> 11. Staffing
> 12. StaffingRequest
> Enter a number from the list above,
> type in the name of another model, or 'q' to exit
> [q] > 4
> Error: Table contrats for model Contrat was not found in datasource default.
> #0 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Model\Model.php(3653): Model->setSource('contrats')
> #1 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1387): Model->getDataSource()
> #2 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Console\Command\Task\ModelTask.php(528): Model->schema(true)
> #3 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Console\Command\Task\ModelTask.php(826): ModelTask->doAssociations(Object(Model))
> #4 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Console\Command\BakeShell.php(174): ModelTask->bake(Object(Model), false)
> #5 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Console\Shell.php(444): BakeShell->all()
> #6 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(212): Shell->runCommand('all', Array)
> #7 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
> #8 D:\workspace-php\Solarium\vendor\cakephp\cakephp\lib\Cake\Console\cake.php(54): ShellDispatcher::run(Array)
> #9 {main}

**Comment by highstrike** [comment]
`Error: Table contrats for model Contrat was not found in datasource default.`

You should probably set MySQL as default datasource? check in `app\Config\database.php`

```
    public $default = array(
        'datasource' => 'Database/Mysql'
```

I'm not sure how this has anything to do with my solr datasource :stuck_out_tongue:

**Comment by Quezako** [comment]
Ok, the table 'contrats' does not exists, its name is ''contrat', without 's'.
I don't know if I should change that in the DB anyway...

**Comment by highstrike** [comment]
Ah, you should probably read the [CakePHP naming conventions](http://book.cakephp.org/2.0/en/getting-started/cakephp-conventions.html) in that case :smile: 

It has to do with the inflector trying to pluralize words. If you want to use bake you **need** to adhere to these conventions

```
- Database table: “people”
- Model class: “Person”, found at /app/Model/Person.php
- Controller class: “PeopleController”, found at /app/Controller/PeopleController.php
- View template, found at /app/View/People/index.ctp
```

**Comment by Quezako** [comment]
Yes, thanks, I remember now... It's been a while I haven't touched CakePHP, almost 2 years! Time goes by...
Thanks, I'll do a few tests and I'll update with the results.

**Comment by highstrike** [comment]
Good luck :wink: 

_Note, this datasource works with cake2, not cake3_
